import '../styles/globals.css';
import { Rubik, Spinnaker } from '@next/font/google';
import Header from '../components/Header';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Footer from '../components/Footer';
import NProgress from 'nprogress';
import '../styles/nprogress.css';
import Head from 'next/head';

NProgress.configure({ showSpinner: false });

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
});

export default function App({ Component, pageProps }) {
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const handleStart = () => {
      // console.log(`Loading: ${url}`);
      NProgress.start();
      console.log('THIS IS START OF CHANGING');
      setLoading(true);
    };

    const handleStop = () => {
      NProgress.done();
      console.log('THIS IS END OF CHANGING');
      setLoading(false);
    };

    router.events.on('routeChangeStart', handleStart);
    router.events.on('routeChangeComplete', handleStop);
    router.events.on('routeChangeError', handleStop);

    console.log(router);

    return () => {
      router.events.off('routeChangeStart', handleStart);
      router.events.off('routeChangeComplete', handleStop);
      router.events.off('routeChangeError', handleStop);
    };
  }, [router]);

  return (
    <>
      <Head>
        <title>Streaming Website</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        className={`${rubik.className} ${loading === true ? 'loading' : ''}`}
      >
        {router.pathname !== '/' ? <Header /> : <></>}
        <main>
          <Component {...pageProps} />
        </main>
        {router.pathname !== '/' ? <Footer /> : <></>}
      </div>
    </>
  );
}
