import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Streaming Website</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.main}>
        <span>What would you like to watch :</span>
        <div className={styles.choiceCont}>
          <ul className={styles.choice}>
            <Link href='/movies'>
              <li>Movies</li>
            </Link>
            <Link href='/anime'>
              <li>Anime</li>
            </Link>
          </ul>
          <div className={styles.halfCircle}></div>
        </div>
      </div>
    </>
  );
}
